### ISSUE TITLE
API

### ISSUE THREAD

**Issue by alexvmarch** [exa-analytics/atomic#13]
From a design standpoint is it nicer to have an API that looks like:
```
universe.primitive_atoms
```
or 
```
universe.get_primitive_atoms(inplace=True)
universe.primitive_atoms
```

In the former approach, primitive_atoms (dataframe) is a property that will be computed if it doesn't exist. In the latter it must first be explicitly computed before it can be accessed. Also, in the latter note that the default is to return the primitive_atoms rather than attach them to the universe.

**Comment by tjduigna** [comment]
if the property is only computed when called for, it seems simpler to have the former. However, if a table such as primitive atoms is something you would want to compute but not store (fast enough to just do on the fly), the flexibility of being able to not attach it to the universe would be useful. I suppose more flexibility is better and somewhat mimics the pandas API.

**Comment by alexvmarch** [comment]
How about a mix? (and primitive_atoms is just an example here; any dataframe will behave this way) 

```
universe.primitive_atoms
```
If the data doesn't exist it will call get_primitive_atoms with inplace=True. But get_primitive_atoms will still be available if the user wants to return the dataframe elsewhere.

**Comment by alexvmarch** [comment]
Closing in favor of the mixed approach detailed above.
