### ISSUE TITLE
field values not getting passed to JS

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/atomic#35]
auni = atomic.Cube(myfilepath).to_universe()
auni

shows the universe and hitting enter inside the isovalue option hits march_cubes2 

console.log(field); // at the top of march_cubes2
returns

Field Object
> values: NewFloat32Array[1]
       0: NaN

On the python side I can look at auni.field and auni.field_values both of which look correct.

**Comment by alexvmarch** [comment]
Hey, why you doing work on vaca? Can you share the cube? What commit are you on?

**Comment by tjduigna** [comment]
Haha, boss put it aptly; 'this is a bad time for you to go on a trip'

I can email you the cube but it should be pretty standard. I am current with the organization fork but a couple commits ahead, tinkering with write_cube.

**Comment by tjduigna** [comment]
As a check, the Cube.to_universe() no longer has the fields attribute. So I believe it should be current.

**Comment by alexvmarch** [comment]
I added support for a default ghost atom type: See commit 5fd89a2. Note that this commit won't work unless you update exa to at least faae5cf. I used the code:

```
cube = atomic.Cube('halide-total-dens.cube').to_universe()
cube.add_field(atomic.Cube('halide-nola-total-dens.cube').field)
cube
```

It seems to render just fine including the ghost atom. The field values seem to all be there too, both in Python and JS. Please close if this is working for you or update me if not. I will be working today so available.

**Comment by tjduigna** [comment]
code:
c1 = 'filename.cube'
auni = atomic.Cube(c1).to_universe()

Stack trace of current error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-9e8d34ae07c0> in <module>()
----> 1 auni = atomic.Cube(c1).to_universe()
      2 #auni

/home/tjd/Programs/analytics-exa/atomic/atomic/filetypes/cube.py in to_universe(self, **kwargs)
    104         '''
    105         return Universe(frame=self.frame, atom=self.atom, meta=self.meta,
--> 106                         field=self.field, **kwargs)
    107 
    108     def _init(self):

<string> in __init__(self, frame, atom, two, field, field_values, unit_atom, projected_atom, periodic_two, molecule, **kwargs)

/home/tjd/miniconda3/lib/python3.5/site-packages/sqlalchemy/orm/state.py in _initialize_instance(*mixed, **kwargs)
    304         except:
    305             with util.safe_reraise():
--> 306                 manager.dispatch.init_failure(self, args, kwargs)
    307 
    308     def get_history(self, key, passive):

/home/tjd/miniconda3/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py in __exit__(self, type_, value, traceback)
     58             exc_type, exc_value, exc_tb = self._exc_info
     59             self._exc_info = None   # remove potential circular references
---> 60             compat.reraise(exc_type, exc_value, exc_tb)
     61         else:
     62             self._exc_info = None   # remove potential circular references

/home/tjd/miniconda3/lib/python3.5/site-packages/sqlalchemy/util/compat.py in reraise(tp, value, tb, cause)
    180         if value.__traceback__ is not tb:
    181             raise value.with_traceback(tb)
--> 182         raise value
    183 
    184     def raise_from_cause(exception, exc_info=None):

/home/tjd/miniconda3/lib/python3.5/site-packages/sqlalchemy/orm/state.py in _initialize_instance(*mixed, **kwargs)
    301 
    302         try:
--> 303             return manager.original_init(*mixed[1:], **kwargs)
    304         except:
    305             with util.safe_reraise():

/home/tjd/Programs/analytics-exa/atomic/atomic/universe.py in __init__(self, frame, atom, two, field, field_values, unit_atom, projected_atom, periodic_two, molecule, **kwargs)
    279             if self._two is None:
    280                 self.compute_two_body()
--> 281             self._update_traits()
    282             self._traits_need_update = False

/home/tjd/Programs/analytics-exa/exa/exa/container.py in _update_traits(self)
    352                 for obj in has_traits.values():
    353                     traits.update(obj._get_traits())
--> 354             self._widget.add_traits(**traits)
    355 
    356 

/home/tjd/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py in add_traits(self, **traits)
    332             if trait.get_metadata('sync'):
    333                  self.keys.append(name)
--> 334                  self.send_state(name)
    335 
    336     #-------------------------------------------------------------------------

/home/tjd/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py in send_state(self, key)
    239                 buffer_keys.append(k)
    240         msg = {'method': 'update', 'state': state, 'buffers': buffer_keys}
--> 241         self._send(msg, buffers=buffers)
    242 
    243     def get_state(self, key=None):

/home/tjd/miniconda3/lib/python3.5/site-packages/ipywidgets/widgets/widget.py in _send(self, msg, buffers)
    449     def _send(self, msg, buffers=None):
    450         """Sends a message to the model in the front-end."""
--> 451         self.comm.send(data=msg, buffers=buffers)
    452 
    453 

/home/tjd/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py in send(self, data, metadata, buffers)
    125         """Send a message to the frontend-side version of this comm"""
    126         self._publish_msg('comm_msg',
--> 127             data=data, metadata=metadata, buffers=buffers,
    128         )
    129 

/home/tjd/miniconda3/lib/python3.5/site-packages/ipykernel/comm/comm.py in _publish_msg(self, msg_type, data, metadata, buffers, **keys)
     73         data = {} if data is None else data
     74         metadata = {} if metadata is None else metadata
---> 75         content = json_clean(dict(data=data, comm_id=self.comm_id, **keys))
     76         self.session.send(self.iopub_socket, msg_type,
     77             content,

/home/tjd/miniconda3/lib/python3.5/site-packages/ipykernel/jsonutil.py in json_clean(obj)
    161         out = {}
    162         for k,v in iteritems(obj):
--> 163             out[unicode_type(k)] = json_clean(v)
    164         return out
    165     if isinstance(obj, datetime):

/home/tjd/miniconda3/lib/python3.5/site-packages/ipykernel/jsonutil.py in json_clean(obj)
    161         out = {}
    162         for k,v in iteritems(obj):
--> 163             out[unicode_type(k)] = json_clean(v)
    164         return out
    165     if isinstance(obj, datetime):

/home/tjd/miniconda3/lib/python3.5/site-packages/ipykernel/jsonutil.py in json_clean(obj)
    161         out = {}
    162         for k,v in iteritems(obj):
--> 163             out[unicode_type(k)] = json_clean(v)
    164         return out
    165     if isinstance(obj, datetime):

/home/tjd/miniconda3/lib/python3.5/site-packages/ipykernel/jsonutil.py in json_clean(obj)
    161         out = {}
    162         for k,v in iteritems(obj):
--> 163             out[unicode_type(k)] = json_clean(v)
    164         return out
    165     if isinstance(obj, datetime):

/home/tjd/miniconda3/lib/python3.5/site-packages/ipykernel/jsonutil.py in json_clean(obj)
    167 
    168     # we don't understand it, it's probably an unserializable object
--> 169     raise ValueError("Can't clean for JSON: %r" % obj)

ValueError: Can't clean for JSON: 16711935

**Comment by alexvmarch** [comment]
Atomic fields now mimic the cube file format; 6f05a00195ed3d92322992f1cc723cc6d8d7ebda

Closing for now.
